/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Donations } from "./Donations";
export * as factories from "./factories";
export { Donations__factory } from "./factories/Donations__factory";
